#!/bin/bash

version=$1
directory=$2

if [ -z "$version" ]; then
   echo "Argument is version suffix"
   exit 1
fi

if [ -z "$directory" ]; then
   echo "Defaulting to 'Shipping' build directory"
   directory="Shipping"
fi

python Tools/Packaging/zip_staging.py "s" "Build/$directory/Windows" "Build/PaperGolf-$version.zip"
printf "\n\n"
python Tools/Packaging/zip_staging.py "d" "Build/$directory/Windows" "Build/PaperGolf-$version-symbols.zip"
