#!/bin/bash

GAME=PaperGolf

version=$1
directory=$2
platform=$3

if [ -z "$version" ]; then
   echo "Argument is version suffix"
   exit 1
fi

if [ -z "$directory" ]; then
   echo "Defaulting to 'Shipping' build directory"
   directory="Shipping"
fi

if [ -z "$platform" ]; then
   echo "Defaulting to 'Windows' platform"
   platform="Windows"
fi

# Copy steam_appid.txt to the game binaries directory
# This is necessary for non-LAN (i.e. steam) multiplayer to work in shipping builds

cp Tools/Packaging/steam_appid.txt "Build/$directory/$platform/$GAME/Binaries/"*
echo "cp Tools/Packaging/steam_appid.txt Build/$directory/$platform/$GAME/Binaries/*"

python Tools/Packaging/zip_staging.py "s" "Build/$directory/$platform" "Build/$GAME-$version-$platform.zip"
printf "\n\n"
python Tools/Packaging/zip_staging.py "d" "Build/$directory/$platform" "Build/$GAME-$version-$platform-symbols.zip"
