#!/bin/bash

GAME=PaperGolf

#TODO: Parameterize this with an input argument so can do for Linux as well
platform=Windows

version=$1
directory=$2

if [ -z "$version" ]; then
   echo "Argument is version suffix"
   exit 1
fi

if [ -z "$directory" ]; then
   echo "Defaulting to 'Shipping' build directory"
   directory="Shipping"
fi

# Copy steam_appid.txt to the game binaries directory
# This is necessary for non-LAN (i.e. steam) multiplayer to work in shipping builds

cp Tools/Packaging/steam_appid.txt "Build/$directory/$platform/$GAME/Binaries/"*
echo "cp Tools/Packaging/steam_appid.txt Build/$directory/$platform/$GAME/Binaries/*"

python Tools/Packaging/zip_staging.py "s" "Build/$directory/$platform" "Build/$GAME-$version.zip"
printf "\n\n"
python Tools/Packaging/zip_staging.py "d" "Build/$directory/$platform" "Build/$GAME-$version-symbols.zip"
