#!/bin/bash

# Get the current branch name
current_branch=$(git rev-parse --abbrev-ref HEAD)

# Check if the current branch is 'main'
if [ "$current_branch" == "main" ]; then
	echo "Zipping Editor Binaries"

	./package_binaries
fi
